version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11

executors:
  fss-executor:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/test-app

jobs:
  build-deploy-staging:
    executor: fss-executor

    steps:
      - attach_workspace:
          at: ~/test-app

      - run:
          name: build
          command: |
            export REACT_APP_ENV=staging
            npm run build

      - aws-s3/sync:
          from: build
          to: 's3://find-support-services-staging.hackney.gov.uk/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true

  build-deploy-production:
    executor: fss-executor

    steps:
      - attach_workspace:
          at: ~/test-app

      - run:
          name: build
          command: |
            export REACT_APP_ENV=production
            npm run build

      - aws-s3/sync:
          from: build
          to: 's3://find-support-services-staging.hackney.gov.uk/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true

workflows:
  version: 2
  continuous-delivery:
    jobs:
      - build-deploy-staging:
          filters:
            branches:
              only:
                - master
      - permit-deploy-production:
          type: approval
          requires:
            - build-deploy-staging
      - build-deploy-production:
          requires:
            - permit-deploy-production